version: '3.8'

services:
  hardhat-node:
    image: ethereum/client-go:latest
    container_name: azora-blockchain-node
    ports:
      - "8545:8545"
      - "8546:8546"
    command: --dev --http --http.addr 0.0.0.0 --http.api eth,net,web3
    networks:
      - azora-network

networks:
  azora-network:
    external: true
