global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'azora-services'
    static_configs:
      - targets:
          - 'host.docker.internal:3059'  # health-monitor
          - 'host.docker.internal:4000'  # api-gateway
          - 'host.docker.internal:3001'  # auth-service
          - 'host.docker.internal:3002'  # azora-education
          - 'host.docker.internal:3003'  # azora-mint
          - 'host.docker.internal:3004'  # azora-forge
          - 'host.docker.internal:3005'  # azora-nexus
          - 'host.docker.internal:3006'  # azora-aegis
