global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "ubuntu_rules.yml"

scrape_configs:
  - job_name: 'ubuntu-tokenomics'
    static_configs:
      - targets: ['ubuntu-tokenomics:3003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongo:27017']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
